### PR TITLE
Replace provider from Addic7ed to Gestdown

### PR DESCRIPTION
**Pull request by Belphemur**
Hello,

I run the service : https://www.gestdown.info. The plan is to provide a proxy and API for Addic7ed.
The advantage of my service are multiple:
1. It reduces tremendously the number of request done on the website
2. I cache the result that I parse and store on my side and any subtitle downloaded making them easily available through the API
3. Currently, handling more than 20M daily request from Bazarr without any issue (thanks to Cloudflare taking care of the caching).
4. The user don't need an account to download subtitles.

### CODE REVIEW

**Comment by ebr11** [comment]
Hi.  You should either create a new plug-in for your service or add it as an option/addition to this one so that it is clear to the user exactly what is happening.

Also, please include a link to your privacy statement for the user to see when sending data to your site.

Thanks.

**Comment by Belphemur** [comment]
The current plugin doesn't really work, Addic7ed have very strong rate limiting. 
Moreover, the current implementation continuously queries the list of show and so for each subtitle it looks for, for each language.

I don't think we should keep the current implementation alive for those reasons.
Now about the Privacy Policy, I don't have one. The service doesn't store anything. There is no way to identify the user (no user account needed, as you can see I removed everything about that), and I don't store logs or IPs. (would be way to costly with the amount of request I currently receive). In the future, I can publish one, but again, if this is a blocker, feel free to close the PR.

Moreover, this is a surprising requirement as I don't think this is currently advertised for any of the Subtitle Plugins.

**Comment by ebr11** [comment]
> Moreover, this is a surprising requirement as I don't think this is currently advertised for any of the Subtitle Plugins.

They are connecting to known public sites whereas you have setup your own service and the plug-in will connect to that.

**Comment by LukePulverenti** [comment]
> I don't think we should keep the current implementation alive for those reasons.
Now about the Privacy Policy, I don't have one. The service doesn't store anything. There is no way to identify the user (no user account needed, as you can see I removed everything about that), and I don't store logs or IPs. (would be way to costly with the amount of request I currently receive). 

You just need to have one on your site in the same way that addic7ed or opensubtitles would. It's really just for users so that they know what to expect.

**Comment by Belphemur** [comment]
@ebr11 & @LukePulverenti Sorry for my harsh tone, writing comment without the morning coffee isn't my best idea.

As requested, I've added a Privacy Policy to the service: https://www.gestdown.info/Privacy

**Comment by LukePulverenti** [comment]
Thanks! So my next questions are, how long has this been running, and second, does it make more sense to replace Addic7ed or to just create a new subtitle plugin called Gestdown?

I know Addic7ed has major limitations, but that could always change, and there's also always the chance that Gestdown could expand beyond it's original purpose of just being a proxy.

**Comment by Belphemur** [comment]
I've been running the project for more or less a year now. To be honest, the website is only to showcase the API, I get no traffic on it in comparison to the API that is used by Bazarr.

Yes, I could create another plugin called Gestdown, after all that would make only minor change to the code, just the plugin file.
Would there be a way to have my plugin used before Addic7ed ? If I'm not wrong, by default it's alphabetical and can be ordered by the user. The reason why I started the service was to reduce the amount of bot querying Addic7ed.
What would be the process to have it included in the list of Emby plugins ?

I don't have any plan to expand the project, to be honest, I already have sooo many ^^, I don't have desire to make it more than it is already.

**Comment by ebr11** [comment]
> What would be the process to have it included in the list of Emby plugins ?

We'd ask that you make it available for a manual download in the plug-ins forum and use that to gauge interest and support.  I don't think it makes sense to have the Addic7ed plug-in go to some other site so it should be its own plug-in so users know exactly what they are doing.  You would want to explain in the description that this is a proxy for Addic7ed so it would be used instead of that plug-in as opposed to with it.

**Comment by ebr11** [comment]
In fact, you may want to call the plug-in "Addic7ed Proxy" or something like that...

**Comment by Belphemur** [comment]
Make sense, I'll make that when I have the time.
So for now, I'll close the PR and will rename my repo to become that plugin :)

ps: I'll also use the new version of the API to get the SeriesServiceIds, thanks @LukePulverenti

**Comment by Belphemur** [comment]
Plugin posted on the forum:
https://emby.media/community/index.php?/topic/117373-gestdown-addic7ed-subtitle-proxy/

**Pull request closed without merging**
